name: Consulta CEP poetry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11' # Versão estável do Python
  # Variável de ambiente para notificação (Requisito)
  EMAIL_TO: ${{ secrets.EMAIL_DE_NOTIFICACAO }} 

jobs:
  # Job 1: Execução dos Testes
  # Roda em paralelo com o 'build', atendendo ao requisito de paralelismo.
  test:
    name: 🧪 Executa os Testes
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Requisito: Instalar software via script/command
      - name: 3. Instalar Poetry e Dependências
        run: |
          pip install poetry
          # Instala dependências do projeto e de desenvolvimento
          poetry install
          
      - name: 4. Rodar Testes Unitários e Gerar Relatório XML
        # Assume que você configurou 'pytest-junitxml' nas dependências de desenvolvimento do Poetry
        run: poetry run pytest tests/ --junitxml=test-report.xml

      # Requisito: Armazenar Relatório de Testes como Artefato
      - name: 5. 📦 Upload do Relatório de Testes
        uses: actions/upload-artifact@v4
        with:
          name: Relatorio-Testes-XML
          path: test-report.xml

  # Job 2: Empacotamento (Build)
  # Roda em paralelo com o 'test'.
  build:
    name: 🏗️ Empacotamento (Build)
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 2. Configurar Versão do Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 3. Instalar Poetry
        run: pip install poetry

      - name: 4. Empacotar o Projeto
        run: poetry build

      # Requisito: Armazenar o Pacote como Artefato
      - name: 5. 📦 Upload do Pacote de Distribuição
        uses: actions/upload-artifact@v4
        with:
          name: Pacote-Distribuicao-CEP
          path: dist/
          
  # Job 3: Notificação (Requisito de 3º job)
  notify:
    name: 📧 Notificação de Status
    runs-on: ubuntu-latest
    # Depende de ambos os jobs anteriores para garantir que os artefatos foram gerados
    needs: [test, build] 
    # Roda sempre, mesmo se 'test' ou 'build' falhar, para enviar a notificação
    if: always() 
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4
        
      # Requisito: Instalar software via script (dando permissão ao notify.sh)
      - name: 2. Dar Permissão de Execução ao Script
        run: chmod +x notify.sh

      # Requisito: Chamar um script para enviar e-mail
      # Passa o status do Job 'test' como argumento
      - name: 3. Executar Script de Notificação
        run: ./notify.sh ${{ needs.test.result }}
        env:
          # Requisito: E-mail não hardcoded, mas sim como variável de ambiente
          EMAIL_TO: ${{ env.EMAIL_TO }}
